version: '3.9'

services:
  app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: app
      DB_PASSWORD: 12345
      DB_PORT: 3306
    

  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ivolve
      MYSQL_USER: app
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - db_mysql:/var/lib/mysql

volumes:
  db_mysql:
