apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce        
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/mysql-data
