# Dockerfile.backend
FROM python:3.9

WORKDIR /app

COPY . .
RUN apt-get update && apt-get install -y iputils-ping && rm -rf /var/lib/apt/lists/*
RUN pip install flask

EXPOSE 5000

CMD ["python", "app.py"]

