---
- name: Install required dependencies
  yum:
    name:
      - wget
      - git
      - fontconfig
      - epel-release
    state: present

- name: Add Adoptium (Temurin) repository
  copy:
    dest: /etc/yum.repos.d/adoptium.repo
    content: |
      [Adoptium]
      name=Adoptium
      baseurl=https://packages.adoptium.net/artifactory/rpm/centos/$releasever/$basearch
      enabled=1
      gpgcheck=1
      gpgkey=https://packages.adoptium.net/artifactory/api/gpg/key/public

- name: Install Temurin 17 JDK (Java 17)
  yum:
    name: temurin-17-jdk
    state: present

- name: Add Jenkins repository
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins GPG key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

- name: Install Jenkins
  yum:
    name: jenkins
    state: present

- name: Enable and start Jenkins service
  service:
    name: jenkins
    state: started
    enabled: yes

